name: avarias_app
description: App Mobile para Gestão de Avarias e Devoluções.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencies identified from code
  http: ^1.2.0
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  
  # Standard icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
